---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: ckad
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-controller
      image: nginx
      

...

