---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: ckad
  labels:
    name: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp
      labels:
        name: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx    
  replicas: 3
  selector:
    matchLabels:
      type: front-end
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%


...