---
apiVersion: v1
kind: Namespace
metadata:
  name: ckad
spec: {}
status: {}

...

apiVersion: v1
kind: Namespace
metadata:
  name: ckad-dev
spec: {}
status: {}

...

apiVersion: v1
kind: Namespace
metadata:
  name: ckad-prod
spec: {}
status: {}

...