---
apiVersion: v1
kind: Namespace
metadata:
  name: ckad-dev
spec: {}

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: ckad-dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 2Gi
    limits.cpu: "20"
    limits.memory: 2Gi

...